blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostDeleteView, PostUpdateView

from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('create', PostCreateView.as_view(), name='post_create'),
    path('update/<int:pk>', PostUpdateView.as_view(), name='post_update'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import ProductListView, ProductDetailView, ContactsTemplateView, ProductUpdateView, ProductCreateView, \
    ProductDeleteView, VersionUpdateView, VersionCreateView, VersionDeleteView, VersionListView, CategoriesListView

from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('create', ProductCreateView.as_view(), name='product_create'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
    path('version/update/<int:pk>', VersionUpdateView.as_view(), name='version_update'),
    path('version/create', VersionCreateView.as_view(), name='version_create'),
    path('version/delete/<int:pk>', VersionDeleteView.as_view(), name='version_delete'),
    path('versions/', VersionListView.as_view(), name='versions'),
    path('categories/', CategoriesListView.as_view(), name='categories'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, recover_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('recover_password/', recover_password, name='recover_password'),
]

catalog/models.py
from random import choice
from tabnanny import verbose

from django.core.files.images import ImageFile
from django.db import models
from django.db.models import ForeignKey, BooleanField
from django.forms import CharField, FloatField

from users.models import User

NULLABLE = {'blank': True, 'null': True}

class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='название')
    description = models.CharField(max_length=500, **NULLABLE, verbose_name='описание')

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='название')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    description = models.CharField(max_length=500, **NULLABLE, verbose_name='описание')
    image = models.ImageField(upload_to='img/', **NULLABLE, verbose_name='превью')
    price = models.FloatField(verbose_name='цена')
    created_at = models.DateTimeField(auto_now_add=True , verbose_name='время создания')
    updated_at =models.DateTimeField(auto_now_add=True, verbose_name='время последнего изменениязшз')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        permissions = [
            ('update_published_status', 'Can cancel publish product'),
            ('update_description', 'Can update product description'),
            ('change_category', 'Can change product category')
        ]

    def __str__(self):
        return f'{self.name}({self.category})'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    number = models.IntegerField(verbose_name='номер')
    name = models.CharField(max_length=255, verbose_name='название', **NULLABLE)
    is_current = models.BooleanField(default=True, verbose_name='признак текущей версии')

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

    def __str__(self):
        return f'Версия {self.number} - {self.name}'

catalog/forms.py
from django import forms
from prompt_toolkit.validation import ValidationError

from catalog.models import Product, Version


class FormStylesMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field.widget.__class__.__name__ == 'CheckboxInput':
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'

class ProductForm(FormStylesMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'category', 'description','price', 'image',)

    def clean_name(self):
        words_prohibited = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево',\
                            'бесплатно', 'обман', 'полиция', 'радар']
        cleaned_data = self.cleaned_data['name']

        check_words = cleaned_data.split()
        for word in check_words:
            if word.lower() in words_prohibited:
                raise forms.ValidationError('Недопустимые слова в названии')
        return cleaned_data

class ProductModeratorForm(FormStylesMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published',)




class VersionForm(FormStylesMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = ('name', 'product', 'number', 'is_current',)

    def clean_is_current(self):
        cleaned_data = self.cleaned_data['is_current']
        product =  self.cleaned_data['product']
        versions = Version.objects.filter(product=product, is_current=True)
        if len(versions) > 1 and cleaned_data:
            raise forms.ValidationError('Допустима только одна текущая версия')
        return cleaned_data

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, ListView, TemplateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version
from catalog.services import get_cached_categories


# Create your views here.
class ProductListView(ListView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        dict_product = {}
        for prod in context_data['object_list']:
            dict_product.setdefault(prod)
            dict_product[prod] = Version.objects.filter(is_current=True, product=prod).first()
        context_data['object_list'] = dict_product
        return context_data

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(is_published=True)
        return qs

class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'

class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products')

    def form_valid(self, form):
        product_form = form.save(commit=False)
        product_form.user = self.request.user
        return super().form_valid(product_form)

class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    success_url = reverse_lazy('catalog:products')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.user:
            return ProductForm
        elif user.has_perm("catalog.update_published_status") and user.has_perm("catalog.update_description") and \
             user.has_perm("catalog.change_category") :
            return ProductModeratorForm
        else:
            raise PermissionDenied

class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:products')

class ContactsTemplateView(TemplateView):
    template_name = "catalog/contacts.html"

class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:products')

class VersionUpdateView(UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:products')

class VersionDeleteView(DeleteView):
    model = Version
    success_url = reverse_lazy('catalog:products')

class VersionListView(ListView):
    model = Version


class CategoriesListView(TemplateView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = get_cached_categories()
        return context

    template_name = "catalog.categories.html"

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% include 'catalog/menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    {% block content%}
    {% endblock %}

    {% include 'catalog/footer.html'%}

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/categories.html
{% extends 'catalog/base.html' %}
{% load custom_tags %}
{% block content %}
    <div class="row text-center">
        <table class="table table-striped">
            <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Имя</th>
        <th scope="col">Номер</th>
        <th scope="col">Текущая</th>
        <th scope="col">Действия</th>
      </tr>
    </thead>
            <tbody>
                {% for category in categories %}
                    <tr>
                      <th scope="row">Категории</th>
                      <td>{{ category.name }}</td>
                      <td>{{ version.description }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content%}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html'%}
{% block content %}
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

catalog/templates/catalog/footer.html
   <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load custom_tags %}
{% block content %}
    <div class="row text-center">
        {% for product in object_list %}
         <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <p class="card-title pricing-card-title">{{ product.price|floatformat:1 }}</p>
                    <img class="card-img-top" src="{{ product.image|change_media_path }}">

                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ product.description|truncatechars:100 }}</li>
                    </ul>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'product_detail' product.pk %}">Подробнее</a>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock content%}

catalog/templates/catalog/menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts'%}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:posts'%}">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:versions'%}">Версиии</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:categories'%}">Категории</a>
        {%if not user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login'%}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register'%}">Зарегистрироваться</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:recover_password'%}">Восстановить пароль</a>
        {% else %}
            <form style="display: inline" method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button class="p-2 btn btn-outline-primary" type="submit">Выйти</button>
            </form>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile'%}">Профиль</a>
        {% endif %}
    </nav>
</div>

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load custom_tags %}
{% block content %}
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                    <h5 class="my-0 font-weight-normal"> {{ product.category }}</h5>
                    <h6 class="my-0 font-weight-normal">{{ product.created_at|date:'d.m.Y' }}</h6>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ product.price }}</h1>
                    <img class="card-img-top" src="{{ product.image|change_media_path }}">
                    <p>{{ product.description|truncatechars:100 }}</p>

                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load custom_tags %}
{% block content %}
    <div class="container">
        <div class="row col-12">
            <div class="card">
                <div class="card-title">Подтверждение удаления</div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <p>Удалить продукт {{ object.name }}?</p>
                        <button class="btn btn-outline-danger" type="submit">Удалить</button>
                        <a class="btn btn-outline-success" href="{% url 'catalog:products' %}">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load custom_tags %}
{% block content %}
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                    <h5 class="my-0 font-weight-normal"> {{ product.category }}</h5>
                    <h6 class="my-0 font-weight-normal">{{ product.created_at|date:'d.m.Y' }}</h6>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ product.price }}</h1>
                    <img class="card-img-top" src="{{ product.image|change_media_path }}">
                    <p>{{ product.description|truncatechars:100 }}</p>

                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% load custom_tags %}
{% block content %}
    <div class="container">
        <div class="row col-12">
            <div class="card">
                <div class="card-title">Продукт</div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-outline-success" type="submit">Добавить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load custom_tags %}
{% block content %}
    <div class="row text-center">
        {% if object_list %}
            {% for product, version in object_list.items %}
                <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                    {% if version is not None%}
                        <p class="card-title pricing-card-title">{{ version }}</p>
                    {% else %}
                        <p class="card-title pricing-card-title">Нет версии</p>
                    {% endif %}
                </div>
                <div class="card-body">
                    <p class="card-title pricing-card-title">{{ product.price|floatformat:1 }}</p>
                    <img class="card-img-top" src="{{ product.image|change_media_path }}">

                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ product.description|truncatechars:100 }}</li>
                    </ul>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary mb-2" href="{% url 'catalog:product_detail' product.pk %}">Подробнее</a>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary mb-2">Купить</button>
                    {% if user.is_authenticated %}
                        {% if user == product.user %}
                           <a type="button" class="btn btn-lg btn-block btn-outline-warning mb-2" href="{% url 'catalog:product_update' product.pk %}">Изменить</a>
                           <a type="button" class="btn btn-lg btn-block btn-outline-danger mb-2" href="{% url 'catalog:product_delete' product.pk %}">Удалить</a>
                        {% elif perms.catalog.update_published_status and perms.catalog.update_description and perms.catalog.change_category %}
                            <a type="button" class="btn btn-lg btn-block btn-outline-warning mb-2" href="{% url 'catalog:product_update' product.pk %}">Изменить</a>
                        {% endif %}
                        <a type="button" class="btn btn-lg btn-block btn-outline-success mb-2" href="{% url 'catalog:product_create' %}">Добавить</a>
                    {% endif %}
                </div>
            </div>
        </div>
            {% endfor %}
        {% else %}
            <p>Каталог пуст</p>
            <a type="button" class="btn btn-lg btn-block btn-outline-success mb-2" href="{% url 'catalog:product_create' %}">Добавить</a>
        {% endif %}
    </div>
{% endblock content%}

catalog/templates/catalog/version_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load custom_tags %}
{% block content %}
    <div class="container">
        <div class="row col-12">
            <div class="card">
                <div class="card-title">Подтверждение удаления</div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <p>Удалить версию {{ object.name }}?</p>
                        <button class="btn btn-outline-danger" type="submit">Удалить</button>
                        <a class="btn btn-outline-success" href="{% url 'catalog:products' %}">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

catalog/templates/catalog/version_form.html
{% extends 'catalog/base.html' %}
{% load custom_tags %}
{% block content %}
    <div class="container">
        <div class="row col-12">
            <div class="card">
                <div class="card-title">Версия</div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-outline-success" type="submit">Добавить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

catalog/templates/catalog/version_list.html
{% extends 'catalog/base.html' %}
{% load custom_tags %}
{% block content %}
    <div class="row text-center">
        <table class="table table-striped">
            <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Имя</th>
        <th scope="col">Номер</th>
        <th scope="col">Текущая</th>
        <th scope="col">Действия</th>
      </tr>
    </thead>
            <tbody>
                {% for version in object_list %}
                    <tr>
                      <th scope="row">{{ version.pk }}</th>
                      <td>{{ version.name }}</td>
                      <td>{{ version.number }}</td>
                      <td>{{ version.is_current }}</td>
                      <td>
                        <a class="btn btn-warning  btn-sm mr-10" href="{% url 'catalog:version_update' version.pk %}">Изменить</a>
                        <a class="btn btn-danger btn-sm mr-10" href="{% url 'catalog:version_delete' version.pk %}">Удалить</a>
                      </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <a class="btn btn-info btn-sm mb-10 mt-10" href="{% url 'catalog:version_create' %}">Добавить версию</a>
    </div>
{% endblock content%}